version: '3'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wouso
      MYSQL_PASSWORD: wouso
      MYSQL_DATABASE: wouso
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/docker/mysql/scripts:/docker-entrypoint-initdb.d

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: wouso
      PMA_PASSWORD: wouso
    ports:
      - 8080:80
    deploy:
      placement:
        constraints: [node.role == manager]

  wouso-backend:
    depends_on:
      - mysql
    image: ihoria/wouso-backend
    restart: unless-stopped
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: wouso
      MYSQL_PASSWORD: wouso
      MYSQL_DATABASE: wouso
      EXPRESS_PORT: 5000
      EXPRESS_HOST: '0.0.0.0'
      SESSION_SECRET: wouso
    ports:
      - 5000:5000
    deploy:
      replicas: 2

  wouso-frontend:
    depends_on:
      - wouso-backend
    image: ihoria/wouso-frontend
    restart: unless-stopped
    ports:
      - 3000:80
    deploy:
      replicas: 2

  grafana:
    depends_on:
      - mysql
    image: grafana/grafana
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3001:3000

volumes:
  mysql-data:
  grafana-data:
