openapi: "3.0.2"
info:
  title: World of USO API
  version: "1.0"
servers:
  - url: http://localhost:5000
paths:
  /ping:
    get:
      tags:
        - Health
      responses:
        "200":
          description: OK
